/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YDrI5w6nW2Q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

export function upload_csv_button() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Upload CSV</CardTitle>
        <CardDescription>Upload a CSV file to import data into your application.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          <Input type="file" accept=".csv" className="sr-only" id="csv-upload" />
          <label
            htmlFor="csv-upload"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
          >
            <div className="mr-2 h-5 w-5" />
            Upload CSV
          </label>
        </div>
      </CardContent>
    </Card>
  )
}
